"""initial schema: organizations, devices, activation_keys

Hand-written, not autogenerated: there is no live Postgres available in the environment this was
authored in to diff against, so this mirrors app/models.py by hand. Run `alembic upgrade head`
against a real database and confirm it applies cleanly before trusting it in production (see
backend/README.md's "Database migrations" section).

Revision ID: 0001
Revises:
Create Date: 2026-10-09
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "organizations",
        sa.Column("org_id", sa.String(), primary_key=True),
        sa.Column("org_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("max_devices", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "devices",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("org_id", sa.String(), sa.ForeignKey("organizations.org_id"), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False, unique=True),
        sa.Column("app_variant", sa.String(), nullable=False),
        sa.Column("app_version", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_devices_org_id", "devices", ["org_id"])

    op.create_table(
        "activation_keys",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("org_id", sa.String(), sa.ForeignKey("organizations.org_id"), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_device_id", sa.String(), nullable=True),
    )
    op.create_index("ix_activation_keys_org_id", "activation_keys", ["org_id"])


def downgrade() -> None:
    op.drop_index("ix_activation_keys_org_id", table_name="activation_keys")
    op.drop_table("activation_keys")
    op.drop_index("ix_devices_org_id", table_name="devices")
    op.drop_table("devices")
    op.drop_table("organizations")
