"""qr tables, menu mirror, orders

Revision ID: 6ae0e2e8214b
Revises: 0001
Create Date: 2026-10-09 21:31:38.185636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae0e2e8214b'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_category_mirror',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'local_id', name='uq_menu_category_org_local')
    )
    op.create_index(op.f('ix_menu_category_mirror_org_id'), 'menu_category_mirror', ['org_id'], unique=False)
    op.create_table('menu_item_mirror',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=False),
    sa.Column('category_local_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'local_id', name='uq_menu_item_org_local')
    )
    op.create_index(op.f('ix_menu_item_mirror_org_id'), 'menu_item_mirror', ['org_id'], unique=False)
    op.create_table('qr_order_counters',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('org_id', 'day')
    )
    op.create_table('qr_tables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('table_local_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tables_org_id'), 'qr_tables', ['org_id'], unique=False)
    op.create_index(op.f('ix_qr_tables_table_local_id'), 'qr_tables', ['table_local_id'], unique=False)
    op.create_index(op.f('ix_qr_tables_token'), 'qr_tables', ['token'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('qr_table_id', sa.String(), nullable=False),
    sa.Column('table_local_id', sa.String(), nullable=False),
    sa.Column('table_label', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mirrored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firestore_session_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.ForeignKeyConstraint(['qr_table_id'], ['qr_tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'idempotency_key', name='uq_orders_org_idempotency')
    )
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_orders_org_id'), 'orders', ['org_id'], unique=False)
    op.create_index(op.f('ix_orders_qr_table_id'), 'orders', ['qr_table_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('menu_item_local_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_orders_qr_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_org_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_qr_tables_token'), table_name='qr_tables')
    op.drop_index(op.f('ix_qr_tables_table_local_id'), table_name='qr_tables')
    op.drop_index(op.f('ix_qr_tables_org_id'), table_name='qr_tables')
    op.drop_table('qr_tables')
    op.drop_table('qr_order_counters')
    op.drop_index(op.f('ix_menu_item_mirror_org_id'), table_name='menu_item_mirror')
    op.drop_table('menu_item_mirror')
    op.drop_index(op.f('ix_menu_category_mirror_org_id'), table_name='menu_category_mirror')
    op.drop_table('menu_category_mirror')
    # ### end Alembic commands ###
